ADD_SCENE(candog, startscreen, Startscreen)
ADD_SCENE(candog, menu, Menu)
ADD_SCENE(candog, scene_1, Scene_1)
ADD_SCENE(candog, scene_2, Scene_2)
ADD_SCENE(candog, scene_3, Scene_3)
ADD_SCENE(candog, scene_4, Scene_4)
ADD_SCENE(candog, settings, Settings)